// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5oIe-dCR7t3DJzj1yeCjJ9bViQ3oVjX8',
    appId: '1:667132836294:web:350fe68f61513ba34e9ac7',
    messagingSenderId: '667132836294',
    projectId: 'mis-labs-project',
    authDomain: 'mis-labs-project.firebaseapp.com',
    storageBucket: 'mis-labs-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW6An3e8-KMMI36sg-trzis0BuiGmekKk',
    appId: '1:667132836294:android:2ef437211c2cdcf54e9ac7',
    messagingSenderId: '667132836294',
    projectId: 'mis-labs-project',
    storageBucket: 'mis-labs-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkxthFrFNa8wl-Sk8ogc17Jt_TYxaqkH8',
    appId: '1:667132836294:ios:e4e35d0ba03bf0d14e9ac7',
    messagingSenderId: '667132836294',
    projectId: 'mis-labs-project',
    storageBucket: 'mis-labs-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2Mis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkxthFrFNa8wl-Sk8ogc17Jt_TYxaqkH8',
    appId: '1:667132836294:ios:e4e35d0ba03bf0d14e9ac7',
    messagingSenderId: '667132836294',
    projectId: 'mis-labs-project',
    storageBucket: 'mis-labs-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2Mis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5oIe-dCR7t3DJzj1yeCjJ9bViQ3oVjX8',
    appId: '1:667132836294:web:005e4a460b8a85244e9ac7',
    messagingSenderId: '667132836294',
    projectId: 'mis-labs-project',
    authDomain: 'mis-labs-project.firebaseapp.com',
    storageBucket: 'mis-labs-project.firebasestorage.app',
  );
}
